custom: ["https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7LZEP85BLPTQG&source=url", "https://www.amazon.com/hz/wishlist/ls/3HMKLRHLLV6FG?ref_=wl_share", "https://www.paypal.me/JoshTurgasen"]
